// source: nuance/asr/v1/resource.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.nuance.asr.v1.EnumResourceReuse', null, global);
goog.exportSymbol('proto.nuance.asr.v1.EnumResourceType', null, global);
goog.exportSymbol('proto.nuance.asr.v1.EnumWeight', null, global);
goog.exportSymbol('proto.nuance.asr.v1.RecognitionResource', null, global);
goog.exportSymbol('proto.nuance.asr.v1.RecognitionResource.ResourceUnionCase', null, global);
goog.exportSymbol('proto.nuance.asr.v1.RecognitionResource.WeightUnionCase', null, global);
goog.exportSymbol('proto.nuance.asr.v1.ResourceReference', null, global);
goog.exportSymbol('proto.nuance.asr.v1.WakeupWord', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nuance.asr.v1.RecognitionResource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.nuance.asr.v1.RecognitionResource.oneofGroups_);
};
goog.inherits(proto.nuance.asr.v1.RecognitionResource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nuance.asr.v1.RecognitionResource.displayName = 'proto.nuance.asr.v1.RecognitionResource';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nuance.asr.v1.ResourceReference = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nuance.asr.v1.ResourceReference, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nuance.asr.v1.ResourceReference.displayName = 'proto.nuance.asr.v1.ResourceReference';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nuance.asr.v1.WakeupWord = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nuance.asr.v1.WakeupWord.repeatedFields_, null);
};
goog.inherits(proto.nuance.asr.v1.WakeupWord, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nuance.asr.v1.WakeupWord.displayName = 'proto.nuance.asr.v1.WakeupWord';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.nuance.asr.v1.RecognitionResource.oneofGroups_ = [[1,2,3,4,8],[5,6]];

/**
 * @enum {number}
 */
proto.nuance.asr.v1.RecognitionResource.ResourceUnionCase = {
  RESOURCE_UNION_NOT_SET: 0,
  EXTERNAL_REFERENCE: 1,
  INLINE_WORDSET: 2,
  BUILTIN: 3,
  INLINE_GRAMMAR: 4,
  WAKEUP_WORD: 8
};

/**
 * @return {proto.nuance.asr.v1.RecognitionResource.ResourceUnionCase}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.getResourceUnionCase = function() {
  return /** @type {proto.nuance.asr.v1.RecognitionResource.ResourceUnionCase} */(jspb.Message.computeOneofCase(this, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[0]));
};

/**
 * @enum {number}
 */
proto.nuance.asr.v1.RecognitionResource.WeightUnionCase = {
  WEIGHT_UNION_NOT_SET: 0,
  WEIGHT_ENUM: 5,
  WEIGHT_VALUE: 6
};

/**
 * @return {proto.nuance.asr.v1.RecognitionResource.WeightUnionCase}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.getWeightUnionCase = function() {
  return /** @type {proto.nuance.asr.v1.RecognitionResource.WeightUnionCase} */(jspb.Message.computeOneofCase(this, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[1]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.toObject = function(opt_includeInstance) {
  return proto.nuance.asr.v1.RecognitionResource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nuance.asr.v1.RecognitionResource} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nuance.asr.v1.RecognitionResource.toObject = function(includeInstance, msg) {
  var f, obj = {
    externalReference: (f = msg.getExternalReference()) && proto.nuance.asr.v1.ResourceReference.toObject(includeInstance, f),
    inlineWordset: jspb.Message.getFieldWithDefault(msg, 2, ""),
    builtin: jspb.Message.getFieldWithDefault(msg, 3, ""),
    inlineGrammar: jspb.Message.getFieldWithDefault(msg, 4, ""),
    wakeupWord: (f = msg.getWakeupWord()) && proto.nuance.asr.v1.WakeupWord.toObject(includeInstance, f),
    weightEnum: jspb.Message.getFieldWithDefault(msg, 5, 0),
    weightValue: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    reuse: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nuance.asr.v1.RecognitionResource}
 */
proto.nuance.asr.v1.RecognitionResource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nuance.asr.v1.RecognitionResource;
  return proto.nuance.asr.v1.RecognitionResource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nuance.asr.v1.RecognitionResource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nuance.asr.v1.RecognitionResource}
 */
proto.nuance.asr.v1.RecognitionResource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.nuance.asr.v1.ResourceReference;
      reader.readMessage(value,proto.nuance.asr.v1.ResourceReference.deserializeBinaryFromReader);
      msg.setExternalReference(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInlineWordset(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBuiltin(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setInlineGrammar(value);
      break;
    case 8:
      var value = new proto.nuance.asr.v1.WakeupWord;
      reader.readMessage(value,proto.nuance.asr.v1.WakeupWord.deserializeBinaryFromReader);
      msg.setWakeupWord(value);
      break;
    case 5:
      var value = /** @type {!proto.nuance.asr.v1.EnumWeight} */ (reader.readEnum());
      msg.setWeightEnum(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setWeightValue(value);
      break;
    case 7:
      var value = /** @type {!proto.nuance.asr.v1.EnumResourceReuse} */ (reader.readEnum());
      msg.setReuse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nuance.asr.v1.RecognitionResource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nuance.asr.v1.RecognitionResource} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nuance.asr.v1.RecognitionResource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExternalReference();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.nuance.asr.v1.ResourceReference.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getWakeupWord();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.nuance.asr.v1.WakeupWord.serializeBinaryToWriter
    );
  }
  f = /** @type {!proto.nuance.asr.v1.EnumWeight} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getReuse();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * optional ResourceReference external_reference = 1;
 * @return {?proto.nuance.asr.v1.ResourceReference}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.getExternalReference = function() {
  return /** @type{?proto.nuance.asr.v1.ResourceReference} */ (
    jspb.Message.getWrapperField(this, proto.nuance.asr.v1.ResourceReference, 1));
};


/**
 * @param {?proto.nuance.asr.v1.ResourceReference|undefined} value
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
*/
proto.nuance.asr.v1.RecognitionResource.prototype.setExternalReference = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.clearExternalReference = function() {
  return this.setExternalReference(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.hasExternalReference = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string inline_wordset = 2;
 * @return {string}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.getInlineWordset = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.setInlineWordset = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.clearInlineWordset = function() {
  return jspb.Message.setOneofField(this, 2, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.hasInlineWordset = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string builtin = 3;
 * @return {string}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.getBuiltin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.setBuiltin = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.clearBuiltin = function() {
  return jspb.Message.setOneofField(this, 3, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.hasBuiltin = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string inline_grammar = 4;
 * @return {string}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.getInlineGrammar = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.setInlineGrammar = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.clearInlineGrammar = function() {
  return jspb.Message.setOneofField(this, 4, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.hasInlineGrammar = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional WakeupWord wakeup_word = 8;
 * @return {?proto.nuance.asr.v1.WakeupWord}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.getWakeupWord = function() {
  return /** @type{?proto.nuance.asr.v1.WakeupWord} */ (
    jspb.Message.getWrapperField(this, proto.nuance.asr.v1.WakeupWord, 8));
};


/**
 * @param {?proto.nuance.asr.v1.WakeupWord|undefined} value
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
*/
proto.nuance.asr.v1.RecognitionResource.prototype.setWakeupWord = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.clearWakeupWord = function() {
  return this.setWakeupWord(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.hasWakeupWord = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional EnumWeight weight_enum = 5;
 * @return {!proto.nuance.asr.v1.EnumWeight}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.getWeightEnum = function() {
  return /** @type {!proto.nuance.asr.v1.EnumWeight} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.nuance.asr.v1.EnumWeight} value
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.setWeightEnum = function(value) {
  return jspb.Message.setOneofField(this, 5, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[1], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.clearWeightEnum = function() {
  return jspb.Message.setOneofField(this, 5, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[1], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.hasWeightEnum = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional float weight_value = 6;
 * @return {number}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.getWeightValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.setWeightValue = function(value) {
  return jspb.Message.setOneofField(this, 6, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[1], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.clearWeightValue = function() {
  return jspb.Message.setOneofField(this, 6, proto.nuance.asr.v1.RecognitionResource.oneofGroups_[1], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.hasWeightValue = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional EnumResourceReuse reuse = 7;
 * @return {!proto.nuance.asr.v1.EnumResourceReuse}
 */
proto.nuance.asr.v1.RecognitionResource.prototype.getReuse = function() {
  return /** @type {!proto.nuance.asr.v1.EnumResourceReuse} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.nuance.asr.v1.EnumResourceReuse} value
 * @return {!proto.nuance.asr.v1.RecognitionResource} returns this
 */
proto.nuance.asr.v1.RecognitionResource.prototype.setReuse = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nuance.asr.v1.ResourceReference.prototype.toObject = function(opt_includeInstance) {
  return proto.nuance.asr.v1.ResourceReference.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nuance.asr.v1.ResourceReference} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nuance.asr.v1.ResourceReference.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    uri: jspb.Message.getFieldWithDefault(msg, 2, ""),
    maskLoadFailures: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    requestTimeoutMs: jspb.Message.getFieldWithDefault(msg, 7, 0),
    headersMap: (f = msg.getHeadersMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nuance.asr.v1.ResourceReference}
 */
proto.nuance.asr.v1.ResourceReference.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nuance.asr.v1.ResourceReference;
  return proto.nuance.asr.v1.ResourceReference.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nuance.asr.v1.ResourceReference} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nuance.asr.v1.ResourceReference}
 */
proto.nuance.asr.v1.ResourceReference.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.nuance.asr.v1.EnumResourceType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMaskLoadFailures(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRequestTimeoutMs(value);
      break;
    case 8:
      var value = msg.getHeadersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nuance.asr.v1.ResourceReference.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nuance.asr.v1.ResourceReference.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nuance.asr.v1.ResourceReference} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nuance.asr.v1.ResourceReference.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUri();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMaskLoadFailures();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getRequestTimeoutMs();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getHeadersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional EnumResourceType type = 1;
 * @return {!proto.nuance.asr.v1.EnumResourceType}
 */
proto.nuance.asr.v1.ResourceReference.prototype.getType = function() {
  return /** @type {!proto.nuance.asr.v1.EnumResourceType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.nuance.asr.v1.EnumResourceType} value
 * @return {!proto.nuance.asr.v1.ResourceReference} returns this
 */
proto.nuance.asr.v1.ResourceReference.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string uri = 2;
 * @return {string}
 */
proto.nuance.asr.v1.ResourceReference.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.nuance.asr.v1.ResourceReference} returns this
 */
proto.nuance.asr.v1.ResourceReference.prototype.setUri = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool mask_load_failures = 3;
 * @return {boolean}
 */
proto.nuance.asr.v1.ResourceReference.prototype.getMaskLoadFailures = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.nuance.asr.v1.ResourceReference} returns this
 */
proto.nuance.asr.v1.ResourceReference.prototype.setMaskLoadFailures = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional uint32 request_timeout_ms = 7;
 * @return {number}
 */
proto.nuance.asr.v1.ResourceReference.prototype.getRequestTimeoutMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.nuance.asr.v1.ResourceReference} returns this
 */
proto.nuance.asr.v1.ResourceReference.prototype.setRequestTimeoutMs = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * map<string, string> headers = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.nuance.asr.v1.ResourceReference.prototype.getHeadersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.nuance.asr.v1.ResourceReference} returns this
 */
proto.nuance.asr.v1.ResourceReference.prototype.clearHeadersMap = function() {
  this.getHeadersMap().clear();
  return this;};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nuance.asr.v1.WakeupWord.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nuance.asr.v1.WakeupWord.prototype.toObject = function(opt_includeInstance) {
  return proto.nuance.asr.v1.WakeupWord.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nuance.asr.v1.WakeupWord} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nuance.asr.v1.WakeupWord.toObject = function(includeInstance, msg) {
  var f, obj = {
    wordsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nuance.asr.v1.WakeupWord}
 */
proto.nuance.asr.v1.WakeupWord.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nuance.asr.v1.WakeupWord;
  return proto.nuance.asr.v1.WakeupWord.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nuance.asr.v1.WakeupWord} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nuance.asr.v1.WakeupWord}
 */
proto.nuance.asr.v1.WakeupWord.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addWords(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nuance.asr.v1.WakeupWord.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nuance.asr.v1.WakeupWord.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nuance.asr.v1.WakeupWord} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nuance.asr.v1.WakeupWord.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWordsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string words = 1;
 * @return {!Array<string>}
 */
proto.nuance.asr.v1.WakeupWord.prototype.getWordsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.nuance.asr.v1.WakeupWord} returns this
 */
proto.nuance.asr.v1.WakeupWord.prototype.setWordsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nuance.asr.v1.WakeupWord} returns this
 */
proto.nuance.asr.v1.WakeupWord.prototype.addWords = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nuance.asr.v1.WakeupWord} returns this
 */
proto.nuance.asr.v1.WakeupWord.prototype.clearWordsList = function() {
  return this.setWordsList([]);
};


/**
 * @enum {number}
 */
proto.nuance.asr.v1.EnumResourceType = {
  UNDEFINED_RESOURCE_TYPE: 0,
  WORDSET: 1,
  COMPILED_WORDSET: 2,
  DOMAIN_LM: 3,
  SPEAKER_PROFILE: 4,
  GRAMMAR: 5,
  SETTINGS: 6
};

/**
 * @enum {number}
 */
proto.nuance.asr.v1.EnumResourceReuse = {
  UNDEFINED_REUSE: 0,
  LOW_REUSE: 1,
  HIGH_REUSE: 5
};

/**
 * @enum {number}
 */
proto.nuance.asr.v1.EnumWeight = {
  DEFAULT_WEIGHT: 0,
  LOWEST: 1,
  LOW: 2,
  MEDIUM: 3,
  HIGH: 4,
  HIGHEST: 5
};

goog.object.extend(exports, proto.nuance.asr.v1);
